name: 📖 Propose Documentation Improvement for Redash LLM Chatbot
description: Help us make our documentation clearer, more comprehensive, and user-friendly.
labels: ["type: documentation", "LLM Chatbot"]
body:
  - type: dropdown
    id: documentation-area
    attributes:
      label: Which area of documentation needs improvement?
      options:
        - Installation
        - Usage
        - Configuration
        - Troubleshooting
        - API Reference
        - Other (please specify)
  - type: textarea
    id: documentation-issue
    attributes:
      label: Describe the issue or suggestion for improvement.
      validations:
        required: true
  - type: textarea
    id: proposed-changes
    attributes:
      label: If you have specific changes in mind, please describe them here.
  - type: textarea
    id: references
    attributes:
      label: Provide links to relevant documentation sections or external resources.
