# Borrowed from https://github.com/skeletonlabs/skeleton

name: 🛠️ New Task to
description: Let us know what you would like to see added.
labels: ["type: task","LLM Chatbot"]
body:
    - type: textarea
      id: task_description
      attributes:
          label: Describe the task in detail, including its purpose, scope, and expected outcomes.
      validations:
        required: true
    - type: dropdown
      id: task_category
      attributes:
          label: What type of pull request would this be?
          options:
              - "Development"
              - "Testing"
              - "Bug Fix"
              - "Docs"
              - "Research"
              - "Other"
    - type: textarea
      id: references
      attributes:
          label: Provide relevant links or additional information.
